sudo: false

language: rust

# NOTE This configuration has only be tested on the stable channel
rust: stable

os:
  - linux
  - osx

env:
  global:
    # This will be part of the release tarball
    # TODO change the project name
    - PROJECT_NAME=rust-everywhere

matrix:
  # Clear the whole matrix
  exclude:
    - os: linux
    - os: osx
  # Add each target manually
  # TODO feel free to remove targets you are not interested in
  # TODO you may want to install packages for specific build jobs, use the addons.apt.packages
  # pattern shown below
  include:
    # WARNING Experimental target. Tests are executed using qemu user emulation, but this approach
    # may have problems when too many threads are spawned. Also, by the next Rust stable release,
    # this target will be replaced by `armv7-unknown-linux-gnueabihf`.
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabihf
      # Extra packages only for this build job
      addons:
        apt:
          packages:
            # Cross compiler and cross compiled C libraries
            - gcc-arm-linux-gnueabihf
            - libc6-armhf-cross
            - libc6-dev-armhf-cross
            # Emulator
            - qemu-user
    - os: linux
      env: TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            # Cross compiler and cross compiled C libraries
            - gcc-multilib
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      env: TARGET=i686-apple-darwin
    - os: osx
      env: TARGET=x86_64-apple-darwin

install:
  - sh ci/install.sh

script:
  - sh ci/script.sh
