[package]
name = "rust_db"
version = "0.1.0"
authors = ["Lucio Franco <lucio.franco@du.edu>"]

[[bin]]
name = "db-server"
path = "src/main.rs"

[[bin]]
name="db-cli"
path = "cli/src/main.rs"

[dependencies]
log = "*"
bincode="*"
rustc-serialize = "0.3.*"
