[package]
name = "rust_db"
version = "0.1.0"
authors = ["Lucio Franco <lucio.franco@du.edu>"]

[[bin]]
name = "rust_db"
path = "src/main.rs"

[dependencies]
log = "*"
bincode="*"
rustc-serialize = "0.3.*"
